services:
  postgres-db-financas-pessoais:
    image: postgres:16-alpine
    container_name: FinancasPessoaisPostgre
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - financas_pessoais_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  financas_pessoais_postgres_data:
    name: financas_pessoais_postgres_data