// <auto-generated />
using System;
using FinancasPessoais.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancasPessoais.Infra.Data.Migrations
{
    [DbContext(typeof(FinancasPessoaisDbContext))]
    [Migration("20260713160016_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Carteira", b =>
                {
                    b.Property<int>("IDCarteira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDCarteira"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMCarteira")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDCarteira");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Carteira", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Despesa", b =>
                {
                    b.Property<int>("IDDespesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDDespesa"));

                    b.Property<string>("DSDespesa")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("DTDespesa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IDCarteira")
                        .HasColumnType("integer");

                    b.Property<int>("IDDespesaFonte")
                        .HasColumnType("integer");

                    b.Property<int>("IDDespesaTipo")
                        .HasColumnType("integer");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMDespesa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("VLDespesa")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("IDDespesa");

                    b.HasIndex("IDCarteira");

                    b.HasIndex("IDDespesaFonte");

                    b.HasIndex("IDDespesaTipo");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Despesa", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.DespesaFonte", b =>
                {
                    b.Property<int>("IDDespesaFonte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDDespesaFonte"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMDespesaFonte")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDDespesaFonte");

                    b.HasIndex("IDUsuario");

                    b.ToTable("DespesaFonte", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.DespesaTipo", b =>
                {
                    b.Property<int>("IDDespesaTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDDespesaTipo"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMDespesaTipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDDespesaTipo");

                    b.HasIndex("IDUsuario");

                    b.ToTable("DespesaTipo", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Emissor", b =>
                {
                    b.Property<int>("IDEmissor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDEmissor"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMEmissor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDEmissor");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Emissor", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Indexador", b =>
                {
                    b.Property<int>("IDIndexador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDIndexador"));

                    b.Property<int>("IDIndiceFinanceiro")
                        .HasColumnType("integer");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMIndexador")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("PCIndiceFinanceiro")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("SGIndexador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IDIndexador");

                    b.HasIndex("IDIndiceFinanceiro");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Indexador", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.IndiceFinanceiro", b =>
                {
                    b.Property<int>("IDIndiceFinanceiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDIndiceFinanceiro"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<byte>("INTaxaPeriodicidade")
                        .HasColumnType("smallint");

                    b.Property<string>("NMIndiceFinanceiro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("VLIndiceFinanceiro")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("IDIndiceFinanceiro");

                    b.HasIndex("IDUsuario");

                    b.ToTable("IndiceFinanceiro", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Investimento", b =>
                {
                    b.Property<int>("IDInvestimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDInvestimento"));

                    b.Property<DateTime>("DTInvestimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DTVencimento")
                        .HasColumnType("date");

                    b.Property<short?>("FLLiquidado")
                        .HasColumnType("smallint");

                    b.Property<int>("IDEmissor")
                        .HasColumnType("integer");

                    b.Property<int>("IDInvestimentoTipo")
                        .HasColumnType("integer");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<byte?>("INTaxaPeriodicidade")
                        .HasColumnType("smallint");

                    b.Property<string>("NMInvestimento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("PCTaxaRentabilidade")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TXAnotacao")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal>("VLInvestimento")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("VLSaldo")
                        .HasColumnType("numeric");

                    b.HasKey("IDInvestimento");

                    b.HasIndex("IDEmissor");

                    b.HasIndex("IDInvestimentoTipo");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Investimento", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.InvestimentoHistorico", b =>
                {
                    b.Property<int>("IDInvestimentoHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDInvestimentoHistorico"));

                    b.Property<DateTime>("DTInvestimentoHistorico")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IDInvestimento")
                        .HasColumnType("integer");

                    b.Property<byte>("INInvestimentoHistorico")
                        .HasColumnType("smallint");

                    b.Property<decimal>("VLInvestimentoHistorico")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("IDInvestimentoHistorico");

                    b.HasIndex("IDInvestimento");

                    b.ToTable("InvestimentoHistorico", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.InvestimentoTipo", b =>
                {
                    b.Property<int>("IDInvestimentoTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDInvestimentoTipo"));

                    b.Property<int?>("IDIndexador")
                        .HasColumnType("integer");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<byte>("INTipoRentabilidade")
                        .HasColumnType("smallint");

                    b.Property<string>("NMInvestimentoTipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SGInvestimentoTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IDInvestimentoTipo");

                    b.HasIndex("IDIndexador");

                    b.HasIndex("IDUsuario");

                    b.ToTable("InvestimentoTipo", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Receita", b =>
                {
                    b.Property<int>("IDReceita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDReceita"));

                    b.Property<string>("DSReceita")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("DTReceita")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IDCarteira")
                        .HasColumnType("integer");

                    b.Property<int>("IDReceitaFonte")
                        .HasColumnType("integer");

                    b.Property<int>("IDReceitaTipo")
                        .HasColumnType("integer");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMReceita")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("VLReceita")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("IDReceita");

                    b.HasIndex("IDCarteira");

                    b.HasIndex("IDReceitaFonte");

                    b.HasIndex("IDReceitaTipo");

                    b.HasIndex("IDUsuario");

                    b.ToTable("Receita", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.ReceitaFonte", b =>
                {
                    b.Property<int>("IDReceitaFonte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDReceitaFonte"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMReceitaFonte")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDReceitaFonte");

                    b.HasIndex("IDUsuario");

                    b.ToTable("ReceitaFonte", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.ReceitaTipo", b =>
                {
                    b.Property<int>("IDReceitaTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDReceitaTipo"));

                    b.Property<int>("IDUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NMReceitaTipo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDReceitaTipo");

                    b.HasIndex("IDUsuario");

                    b.ToTable("ReceitaTipo", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IDUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IDUsuario"));

                    b.Property<string>("CDSenha")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NMLogin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NMUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDUsuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Carteira", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Carteiras")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Despesa", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Carteira", "Carteira")
                        .WithMany("Despesas")
                        .HasForeignKey("IDCarteira")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.DespesaFonte", "DespesaFonte")
                        .WithMany("Despesas")
                        .HasForeignKey("IDDespesaFonte")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.DespesaTipo", "DespesaTipo")
                        .WithMany("Despesas")
                        .HasForeignKey("IDDespesaTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Despesas")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carteira");

                    b.Navigation("DespesaFonte");

                    b.Navigation("DespesaTipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.DespesaFonte", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Usuario", "Usuario")
                        .WithMany("DespesasFontes")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.DespesaTipo", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Usuario", "Usuario")
                        .WithMany("DespesasTipos")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Emissor", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Emissores")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Indexador", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.IndiceFinanceiro", "IndiceFinanceiro")
                        .WithMany("Indexadores")
                        .HasForeignKey("IDIndiceFinanceiro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Indexadores")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndiceFinanceiro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.IndiceFinanceiro", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Usuario", "Usuario")
                        .WithMany("IndicesFinanceiros")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Investimento", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Emissor", "Emissor")
                        .WithMany("Investimentos")
                        .HasForeignKey("IDEmissor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.InvestimentoTipo", "InvestimentoTipo")
                        .WithMany("Investimentos")
                        .HasForeignKey("IDInvestimentoTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Investimentos")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emissor");

                    b.Navigation("InvestimentoTipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.InvestimentoHistorico", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Investimento", "Investimento")
                        .WithMany("InvestimentosHistoricos")
                        .HasForeignKey("IDInvestimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investimento");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.InvestimentoTipo", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Indexador", "Indexador")
                        .WithMany("InvestimentosTipos")
                        .HasForeignKey("IDIndexador")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinancasPessoais.Domain.Entities.Usuario", "Usuario")
                        .WithMany("InvestimentosTipos")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indexador");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Receita", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Carteira", "Carteira")
                        .WithMany("Receitas")
                        .HasForeignKey("IDCarteira")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.ReceitaFonte", "ReceitaFonte")
                        .WithMany("Receitas")
                        .HasForeignKey("IDReceitaFonte")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.ReceitaTipo", "ReceitaTipo")
                        .WithMany("Receitas")
                        .HasForeignKey("IDReceitaTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Receitas")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carteira");

                    b.Navigation("ReceitaFonte");

                    b.Navigation("ReceitaTipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.ReceitaFonte", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ReceitasFontes")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.ReceitaTipo", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ReceitasTipos")
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Carteira", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.DespesaFonte", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.DespesaTipo", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Emissor", b =>
                {
                    b.Navigation("Investimentos");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Indexador", b =>
                {
                    b.Navigation("InvestimentosTipos");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.IndiceFinanceiro", b =>
                {
                    b.Navigation("Indexadores");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Investimento", b =>
                {
                    b.Navigation("InvestimentosHistoricos");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.InvestimentoTipo", b =>
                {
                    b.Navigation("Investimentos");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.ReceitaFonte", b =>
                {
                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.ReceitaTipo", b =>
                {
                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Carteiras");

                    b.Navigation("Despesas");

                    b.Navigation("DespesasFontes");

                    b.Navigation("DespesasTipos");

                    b.Navigation("Emissores");

                    b.Navigation("Indexadores");

                    b.Navigation("IndicesFinanceiros");

                    b.Navigation("Investimentos");

                    b.Navigation("InvestimentosTipos");

                    b.Navigation("Receitas");

                    b.Navigation("ReceitasFontes");

                    b.Navigation("ReceitasTipos");
                });
#pragma warning restore 612, 618
        }
    }
}
